apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spiffe-demo

resources:
- serviceaccount.yaml
- scc.yaml
- scc-rolebinding.yaml
- configmap.yaml
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/pavelanni/klaviger
  newTag: "3311440"
