apiVersion: v1
kind: ServiceAccount
metadata:
  name: summarizer-tech-klaviger
  labels:
    app.kubernetes.io/name: summarizer-tech-klaviger
    app.kubernetes.io/component: agent
    kagenti.io/type: agent
